
import Footer from '@/components/Footer/Footer'
import Navbar from '@/components/shared/Navbar/Navbar'



// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function Template({ children }) {
    return (
        <div
        >
            <Navbar />
            <div className='min-h-[calc(100vh-110px-492px)]'>
                {children}
            </div>
            <Footer />

        </div>

    )
}
