
import Navbar from '@/components/shared/Navbar/Navbar'



// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function Template({ children }) {
    return (
        <div
        >
            <Navbar />
            {children}

        </div>

    )
}
